name: C++ Build and Run

on:
  push:
    branches:
      - main
  pull_request:

env:
  DYNAMIC_IP: ping -n 1 nodepingreturn.jarzaclay.repl.co | Select-String -Pattern "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}" | ForEach-Object { $_.Matches[0].Value }).Trim() | Select-Object -First 1

jobs:
  build_and_run:
    name: Build and Run C++ Server
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: JarzaClay/visca-control
          path: visca-control

      - name: Set up g++ with Chocolatey
        run: |
          choco install mingw -y
        shell: powershell

      - name: Compile C++ Files
        run: |
          foreach ($file in Get-ChildItem -Path . -Filter "*.cpp" -Recurse) {
            & g++ $file.FullName -o "$($file.FullName.Replace('.cpp', ''))" -lws2_32
          }
        shell: powershell

      - name: Run C++ Programs
        run: |
          echo "IP: ${{ vars.DYNAMIC_IP }}"
          foreach ($file in Get-ChildItem -Path . -Filter "*.exe" -Recurse) {
            if ($file.Name -notlike "*.cpp") { # Skip the .cpp files themselves
              cmd /c "$file -i ${{ vars.DYNAMIC_IP }} -p 80 -m 01 -l"
            }
          }
        shell: powershell

      - name: Create 'bin' directory and move compiled files
        run: |
          New-Item -ItemType Directory -Force -Path bin
          Move-Item -Path *.exe -Destination bin -Force
        shell: powershell

      - name: Upload 'bin' folder as artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-binaries
          path: bin

  deploy_artifact:
    name: Deploy Artifact to 'bin' folder
    needs: build_and_run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download 'compiled-binaries' artifact
        uses: actions/download-artifact@v2
        with:
          name: compiled-binaries

      - name: Extract artifact contents to 'bin' folder
        run: |
          unzip -q compiled-binaries.zip -d bin
        shell: bash

      - name: Commit changes to 'bin' folder
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add bin/
          git commit -m "Update compiled binaries" -a || echo "No changes to commit"
        shell: bash

      - name: Push changes to the repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
