name: C++ Build, Run, and Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  DYNAMIC_IP: ping -n 1 nodepingreturn.jarzaclay.repl.co | Select-String -Pattern "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}" | ForEach-Object { $_.Matches[0].Value }.Trim() | Select-Object -First 1

jobs:
  build_and_run:
    name: Build and Run C++ Server
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: JarzaClay/visca-control
          path: D:\a\visca-control\visca-control\repo

      - name: Set up C++ compilers with Chocolatey
        run: |
          choco install mingw -y
        shell: powershell

      - name: Compile C++ Files Dynamically with g++ # G++ dynamic w/ non-system dlls static
        run: |
          foreach ($file in Get-ChildItem -Path D:\a\visca-control\visca-control\repo\ -Filter "*.cpp" -Recurse) {
            echo "$($file.Name.Replace('.cpp', ''))"
            & g++ "$($file.FullName)" -o "$($file.FullName.Replace('.cpp', ''))"  -lws2_32 -static-libgcc -static-libstdc++
          }
        shell: powershell

      - name: Compile C++ Files Statically with g++ # G++ static
        run: |
          foreach ($file in Get-ChildItem -Path D:\a\visca-control\visca-control\repo\ -Filter "*.cpp" -Recurse) {
            echo "$($file.Name.Replace('.cpp', ''))"
            & g++ "$($file.FullName)" -o "$($file.FullName.Replace('.cpp', ''))_static" -lws2_32 -static
          }
        shell: powershell

      - name: Run C++ Programs
        run: |
          echo "IP: ${{ vars.DYNAMIC_IP }}"
          foreach ($file in Get-ChildItem -Path D:\a\visca-control\visca-control\repo\ -Filter "*.exe" -Recurse) {
            if ("$($file.FullName -notlike "*.cpp")") {
              cmd /c "$($file.FullName) -i ${{ vars.DYNAMIC_IP }} -p 80 -m 01 -l"
            }
          }
        shell: powershell

      - name: Create 'bin' directory with both compilation directories and move compiled files
        run: |
          New-Item -ItemType Directory -Force -Path D:\a\visca-control\visca-control\repo\bin
          New-Item -ItemType Directory -Force -Path D:\a\visca-control\visca-control\repo\bin\dynamic
          New-Item -ItemType Directory -Force -Path D:\a\visca-control\visca-control\repo\bin\static
          Move-Item -Path D:\a\visca-control\visca-control\repo\*_static.exe -Destination D:\a\visca-control\visca-control\repo\bin\static -Force
          foreach ($file in Get-ChildItem -Path D:\a\visca-control\visca-control\repo\bin\static\ -Filter "*.exe" -Recurse) {
            Rename-Item -Path "D:\a\visca-control\visca-control\repo\bin\static\$file" -NewName "$($file.Name.Replace('_static.exe', '.exe'))"
          }
          Move-Item -Path D:\a\visca-control\visca-control\repo\*.exe -Destination D:\a\visca-control\visca-control\repo\bin\dynamic -Force
          ls D:\a\visca-control\visca-control\repo\bin\static\
        shell: powershell

      - name: Upload 'bin' folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-binaries
          path: D:\a\visca-control\visca-control\repo\bin

  test_executables:
    name: Test compiled executables on a fresh Windows install
    needs: build_and_run
    runs-on: windows-latest

    steps:
      - name: Download 'compiled-binaries' artifact
        uses: actions/download-artifact@v3
        with:
          name: compiled-binaries
          path: D:\a\visca-control\visca-control\bin

      - name: Ensure the Windows install is clean
        run: |
          choco uninstall all -y
        shell: powershell

      - name: Run compiled binary files
        run: |
          echo "IP: ${{ vars.DYNAMIC_IP }}"
          foreach ($file in Get-ChildItem -Path D:\a\visca-control\visca-control\bin\dynamic -Filter "*.exe" -Recurse) {
            cmd /c "$($file.FullName) -i ${{ vars.DYNAMIC_IP }} -p 80 -m 01 -l"
          }
          echo "Dynamic binaries OK!"

          foreach ($file in Get-ChildItem -Path D:\a\visca-control\visca-control\bin\static -Filter "*.exe" -Recurse) {
            cmd /c "$($file.FullName) -i ${{ vars.DYNAMIC_IP }} -p 80 -m 01 -l"
          }
          echo "Static binaries OK!"
        shell: powershell

  deploy_artifact:
    name: Deploy Artifact to 'bin' folder
    needs: test_executables
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: JarzaClay/visca-control
          path: /home/runner/work/visca-control/visca-control/path/

      - name: Download 'compiled-binaries' artifact
        uses: actions/download-artifact@v3
        with:
          name: compiled-binaries
          path: /home/runner/work/visca-control/visca-control/path/bin/

      - name: Commit changes to 'bin' folder
        run: |
          cd /home/runner/work/visca-control/visca-control/path/bin/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update compiled binaries" -a || echo "No changes to commit"
        shell: bash

      - name: Push changes to the repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          directory: /home/runner/work/visca-control/visca-control/path/
