name: C++ Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build C++ Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up g++ on Ubuntu
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: Expose Port
        run: |
          echo "Port 1258" >> ~/.bashrc
        shell: bash

      - name: Compile C++ Files
        run: |
          for file in $(find . -name "*.cpp"); do
            g++ "$file" -o "${file%.cpp}"
          done

      - name: Run C++ Programs
        run: |
          for file in $(find . -type f -executable); do
            if [[ "$file" != *".cpp" ]]; then # Skip the .cpp files themselves
              ./"$file" -i 127.0.0.1 -p 1258 -m 01 -l
            fi
          done
