name: C++ Build and Run

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_run:
    name: Build and Run C++ Server
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up g++ on Windows
        uses: mstf/Cpp-Setup@v1

      - name: Expose Port
        run: |
          [Environment]::SetEnvironmentVariable("PORT", "1258", [EnvironmentVariableTarget]::User)
        shell: powershell

      - name: Compile C++ Files
        run: |
          foreach ($file in Get-ChildItem -Path . -Filter "*.cpp" -Recurse) {
            & g++ $file.FullName -o "$($file.FullName.Replace('.cpp', ''))"
          }
        shell: powershell

      - name: Run C++ Programs
        run: |
          foreach ($file in Get-ChildItem -Path . -Filter "*.exe" -Recurse) {
            if ($file.Name -notlike "*.cpp.exe") { # Skip the .cpp files themselves
              & $file.FullName -i 127.0.0.1 -p $env:PORT -m 01 -l
            }
          }
        shell: powershell
