name: C++ Build and Run

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_run:
    name: Build and Run C++ Server
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download and Extract Ncat
        run: |
          $url = 'https://nmap.org/dist/ncat-portable-5.59BETA1.zip'
          $zipPath = "$env:TEMP\ncat-portable-5.59BETA1.zip"
          $extractPath = "$env:TEMP\ncat"
          Invoke-WebRequest -Uri $url -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $extractPath
          Move-Item -Path "$extractPath\ncat-portable-5.59BETA1\ncat.exe" -Destination "$env:USERPROFILE\ncat.exe"
          Remove-Item -Path $zipPath, $extractPath -Force -Recurse
        shell: powershell

      - name: Set up g++ with Chocolatey
        run: |
          choco install mingw -y
        shell: powershell

      - name: Compile C++ Files
        run: |
          foreach ($file in Get-ChildItem -Path . -Filter "*.cpp" -Recurse) {
            & g++ $file.FullName -o "$($file.FullName.Replace('.cpp', ''))" -lws2_32
          }
        shell: powershell

      - name: Run C++ Programs with ncat
        run: |
          cmd /c "$env:USERPROFILE\ncat.exe -l -p 1258 -k"
          foreach ($file in Get-ChildItem -Path . -Filter "*.exe" -Recurse) {
            if ($file.Name -notlike "*.cpp.exe") { # Skip the .cpp files themselves
              cmd /c "$file -i 127.0.0.1 -p 1258 -m 01 -l"
            }
          }
        shell: powershell
